apiVersion: apps/v1
kind: Deployment
metadata:
  name: sebastienattal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sebastienattal
  template:
    metadata:
      labels:
        app: sebastienattal
    spec:
      containers:
      - name: sebastienattal
        image: php:8.0-apache

---

apiVersion: v1
kind: Service
metadata:
  name: sebastienattal
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP
  ports:
  - name: "sebastienattal"
    port: 8080
  selector:
    app: sebastienattal